name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential debhelper dh-python python3-all pybuild-plugin-pyproject
        sudo apt install -y python3-gi gir1.2-gtk-3.0 gir1.2-notify-0.7 gir1.2-ayatanaappindicator3-0.1 libayatana-appindicator3-1 python3-requests
    
    - name: Build .deb package
      run: |
        dpkg-buildpackage -us -uc -b
    
    - name: Upload .deb to release
      uses: softprops/action-gh-release@v1
      with:
        files: ../vercel-deployments_*.deb
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
